// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
)

// Chatroom is the golang structure for table chatroom.
type Chatroom internal.Chatroom

// Fill with you ideas below.
