// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
)

// ChatroomClient is the golang structure for table chatroom_client.
type ChatroomClient internal.ChatroomClient

// Fill with you ideas below.
