// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
)

// ChatRecord is the golang structure for table chat_record.
type ChatRecord internal.ChatRecord

// Fill with you ideas below.
