// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
)

// ChatroomRecord is the golang structure for table chatroom_record.
type ChatroomRecord internal.ChatroomRecord

// Fill with you ideas below.
