// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
)

// ChatroomUser is the golang structure for table chatroom_user.
type ChatroomUser internal.ChatroomUser

type ChatroomReq struct {
	UserId int
	CheckedFriends []int
}
// Fill with you ideas below.
