// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
)

// Client is the golang structure for table client.
type Client internal.Client

// Fill with you ideas below.
