// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
)

// Friendship is the golang structure for table friendship.
type Friendship internal.Friendship

// Fill with you ideas below.
