// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-admin-api/app/model/internal"
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User internal.User

type UserReq struct {
	Id int
	Nickname  string `v:"required|length:6,16#账号不能为空|账号长度应当在:min到:max之间"`
	CreateTime *gtime.Time
	Uid string
}
// Fill with you ideas below.
