version: '3'
services:
  gf-admin-api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8199:8199"
    links:
      - mysql
      - redis
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "13306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 111111
      MYSQL_ROOT_PASSWORD: 111111
  redis:
    image: redis
    hostname: "redis"
    ports:
      - "16379:6379"
    container_name: redis
    restart: always