// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Chatroom is the golang structure for table chatroom.
type Chatroom struct {
	Id         int         `orm:"id,primary"  json:"id"`         // id
	Name       string      `orm:"name"        json:"name"`       // 群聊名称
	Status     int         `orm:"status"      json:"status"`     // 状态(1:正常,0:不可用)
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 创建时间
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
}
