// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ChatRecord is the golang structure for table chat_record.
type ChatRecord struct {
	Id       int         `orm:"id,primary" json:"id"`       // id
	Sender   string      `orm:"sender"     json:"sender"`   // 发送人
	Receiver string      `orm:"receiver"   json:"receiver"` // 接收人
	Content  string      `orm:"content"    json:"content"`  // 内容
	Time     *gtime.Time `orm:"time"       json:"time"`     // 时间
}
