// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// ChatroomClient is the golang structure for table chatroom_client.
type ChatroomClient struct {
	Id       uint   `orm:"id,primary" json:"id"`       // id
	RoomId   uint   `orm:"room_id"    json:"roomId"`   // 群聊房间id
	Uid      string `orm:"uid"        json:"uid"`      // 用户id
	Nickname string `orm:"nickname"   json:"nickname"` // 昵称
	IsOwner  int    `orm:"is_owner"   json:"isOwner"`  // 是否是群主
}
