// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Client is the golang structure for table client.
type Client struct {
	Id         int         `orm:"id,primary"  json:"id"`         // 自增
	Name       string      `orm:"name"        json:"name"`       // 客户名称
	KfId       string      `orm:"kf_id"       json:"kfId"`       // 接到客服id
	LatestTime *gtime.Time `orm:"latest_time" json:"latestTime"` // 最新消息时间
	Uid        string      `orm:"uid,unique"  json:"uid"`        // 客户唯一id
	JoinTime   *gtime.Time `orm:"join_time"   json:"joinTime"`   // 加入时间
	Status     int         `orm:"status"      json:"status"`     // 对话状态（1：机器人，2：排队中，3：人工对话）
}
