// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         int         `orm:"id,primary"  json:"id"`         // 自增
	Nickname   string      `orm:"nickname"    json:"nickname"`   // 客户名称
	Uid        string      `orm:"uid,unique"  json:"uid"`        // 客户唯一id
	Phone      string      `orm:"phone"       json:"phone"`      // 手机号
	Avatar     string      `orm:"avatar"      json:"avatar"`     // 头像
	Status     int         `orm:"status"      json:"status"`     // 对话状态（1：机器人，2：排队中，3：人工对话）
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 加入时间
}
