// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         uint        `orm:"id,primary"  json:"id"`         // id
	Username   string      `orm:"username"    json:"username"`   // 用户名
	Nickname   string      `orm:"nickname"    json:"nickname"`   // 昵称
	Password   string      `orm:"password"    json:"password"`   // 密码
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 创建时间
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间
	Status     int         `orm:"status"      json:"status"`     // 状态，1：可用，0：停用
}
