// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-admin-api/app/dao/internal"
)

// adminUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type adminUserDao struct {
	internal.AdminUserDao
}

var (
	// AdminUser is globally public accessible object for table admin_user operations.
	AdminUser = adminUserDao{
		internal.AdminUser,
	}
)

// Fill with you ideas below.
