// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-admin-api/app/dao/internal"
)

// chatroomClientDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type chatroomClientDao struct {
	internal.ChatroomClientDao
}

var (
	// ChatroomClient is globally public accessible object for table chatroom_client operations.
	ChatroomClient = chatroomClientDao{
		internal.ChatroomClient,
	}
)

// Fill with you ideas below.
