// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-admin-api/app/dao/internal"
)

// chatroomUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type chatroomUserDao struct {
	internal.ChatroomUserDao
}

var (
	// ChatroomUser is globally public accessible object for table chatroom_user operations.
	ChatroomUser = chatroomUserDao{
		internal.ChatroomUser,
	}
)

// Fill with you ideas below.
