// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-admin-api/app/dao/internal"
)

// chatroomRecordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type chatroomRecordDao struct {
	internal.ChatroomRecordDao
}

var (
	// ChatroomRecord is globally public accessible object for table chatroom_record operations.
	ChatroomRecord = chatroomRecordDao{
		internal.ChatroomRecord,
	}
)

// Fill with you ideas below.
