// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-admin-api/app/dao/internal"
)

// chatroomDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type chatroomDao struct {
	internal.ChatroomDao
}

var (
	// Chatroom is globally public accessible object for table chatroom operations.
	Chatroom = chatroomDao{
		internal.Chatroom,
	}
)

// Fill with you ideas below.
