// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-admin-api/app/dao/internal"
)

// clientDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type clientDao struct {
	internal.ClientDao
}

var (
	// Client is globally public accessible object for table client operations.
	Client = clientDao{
		internal.Client,
	}
)

// Fill with you ideas below.
