// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-admin-api/app/dao/internal"
)

// friendshipDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type friendshipDao struct {
	internal.FriendshipDao
}

var (
	// Friendship is globally public accessible object for table friendship operations.
	Friendship = friendshipDao{
		internal.Friendship,
	}
)

// Fill with you ideas below.
